import { Project, Service, ArtPiece } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'inbox-mind',
    year: '2025',
    title: 'InboxMind AI',
    description: 'Smart Email & Lead Triage. Automated system utilizing AI to classify incoming emails, identify business opportunities, prioritize intent, and execute CRM actions without human intervention.',
    tags: ['n8n', 'OpenAI', 'Automation'],
    gradient: 'from-[#0d1117] to-[#161b22]'
  },
  {
    id: 'lead-mind',
    year: '2025',
    title: 'LeadMind AI',
    description: 'Automated Lead Qualification Engine. Backend architecture using webhooks and AI to score incoming leads based on intent, triggering specific sales workflows and database structuring.',
    tags: ['Webhooks', 'Lead Scoring', 'System Design'],
    gradient: 'from-[#1a1a0f] to-[#2b2b1a]'
  },
  {
    id: 'reservo-bot',
    year: '2025',
    title: 'ReservoBot AI',
    description: 'Voice & Chat Booking Assistant. Conversational AI that extracts booking details (date, time, pax) from natural language and validates them against real-time calendar availability.',
    tags: ['NLP', 'Voice AI', 'Chatbots'],
    gradient: 'from-[#1c1917] to-[#292524]'
  },
  {
    id: 'el-saman',
    year: '2024',
    title: 'El Samán',
    description: 'Design and development of a modern website for a premium interior finishes & flooring brand. Translating physical texture to digital space.',
    tags: ['Web Experience', 'Branding', 'React'],
    gradient: 'from-[#1a1a1a] to-[#0f0f0f]'
  },
  {
    id: 'ai-day-progress',
    year: '2025',
    title: 'AI Day Progress',
    description: 'Personal productivity ecosystem powered by the OpenAI API to track, analyze, and reflect on daily momentum in real-time.',
    tags: ['OpenAI API', 'Productivity', 'App'],
    gradient: 'from-[#0a0a0a] to-[#151515]'
  }
];

export const SERVICES: Service[] = [
  {
    id: 'automation',
    number: '01',
    title: 'AI AUTOMATIONS',
    description: 'Removing bottlenecks in leads and operations. Smart flows that actually run.',
    tech: ['n8n', 'OpenAI', 'Webhooks', 'CRM Integrations']
  },
  {
    id: 'apps',
    number: '02',
    title: 'INTERNAL TOOLS',
    description: 'Prototyping fast. Connecting AI intelligence with real-world business workflows.',
    tech: ['OpenAI API', 'React', 'System Architecture']
  },
  {
    id: 'web',
    number: '03',
    title: 'WEB EXPERIENCES',
    description: 'Modern presence for brands that need to stand out. Cold, precise, functional.',
    tech: ['Next.js', 'Tailwind', 'Motion', 'Vercel']
  },
  {
    id: 'data',
    number: '04',
    title: 'DATA & ENG.',
    description: 'Bridging code and structure. Clean foundations and data that tells a story.',
    tech: ['Power BI', '.NET MAUI', 'SQL', 'AWS']
  }
];

export const ARTWORKS: ArtPiece[] = [
  {
    id: '1',
    title: 'Neural Architecture',
    caption: 'Exploring brutalist structures generated by noise.',
    src: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?q=80&w=800&auto=format&fit=crop',
    aspect: 'portrait'
  },
  {
    id: '2',
    title: 'Void Interface',
    caption: 'UI concepts for zero-gravity environments.',
    src: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    aspect: 'landscape'
  },
  {
    id: '4',
    title: 'Data Erosion',
    caption: 'Visualizing packet loss as physical decay.',
    src: 'https://i.imgur.com/mDpKrPH.jpeg',
    aspect: 'portrait'
  },
  {
    id: '5',
    title: 'Synthetic Flora',
    caption: 'Organic growth algorithms in digital space.',
    src: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=800&auto=format&fit=crop',
    aspect: 'landscape'
  },
  {
    id: '6',
    title: 'Tokyo Ghost',
    caption: 'Main character energy. The protagonist of the simulation.',
    src: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    aspect: 'portrait'
  }
];